---
- name: Execute Tests with Jsnapy
  hosts: all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"
    
  tasks:
    - name: "TEST1 - Check Interfaces are UP"
      ignore_errors: true
      juniper.device.jsnapy:
        dir: "~/resources"
        config_file: "test_junos_interface.yml"        
        logfile: "jsnapy_tests.log"
      register: test1
    # - debug: var=test1 verbosity=2

    - assert:
        that:
          - "test1.passPercentage == 100"
