---
- name: Execute Tests with Jsnapy
  hosts: all
  connection: local
  gather_facts: no
  vars:
    user: "{{ANSIBLE_NET_USERNAME}}"
    passwd: "{{ANSIBLE_NET_PASSWORD}}"
    
  tasks:
    - name: "TEST1 - Check Interfaces are UP"
      ignore_errors: true
      juniper.device.jsnapy:
        test_files: resources/test_junos_interface.yml
        action: snapcheck
        logfile: jsnap.log
      register: test1
    # - debug: var=test1 verbosity=2

    - name: "TEST2 - Check Available Storage"
      ignore_errors: true
      juniper.device.jsnapy:
        test_files: resources/test_junos_storage.yml
        action: snapcheck
        logfile: jsnap.log
      register: test2

    - assert:
        that:
          - "test1.passPercentage == 100"
          - "test2.passPercentage == 100"
